### ISSUE TITLE
希望能介绍下针对大内存性能优化，界面卡顿UI渲染优化做了什么处理？

### ISSUE THREAD

**Issue by 452MJ** [ctripcorp/CRN#10]
希望能介绍下针对大内存性能优化，界面卡顿UI渲染优化做了什么处理？因为项目也已经开发有一段时间，整体迁移至crn成本有点高

**Comment by blackwuxin** [comment]
- 先渲染一个简单的视图，比如使用骨架屏，然后延迟渲染完整的UI。
- 对于拥有长列表的页面，可以只渲染首屏，当滑动的时候再添加剩余的View。
- 减少重绘次数，使用`shouldComponetUpdate` ,`PureComponent`。
- 列表使用`FlatList`替换`ListView`，`ListView`有内存问题。
- 动画优先使用`Animated(useNativeDriver:true)`,`Style transform(translateX/Y,scale,rotate)`

**Comment by 452MJ** [comment]
@blackwuxin 骨架屏是在原生端初始化时展示吗

**Comment by blackwuxin** [comment]
骨架图在JS端显示即可。

进入RN首屏时候先显示骨架图，然后根据网络请求或者其他逻辑需要改`state`更新试图。

**Comment by 452MJ** [comment]
谢啦~
