### ISSUE TITLE
crn-cli start 启动报错

### ISSUE THREAD

**Issue by xiamingyu** [ctripcorp/CRN#14]
![image](https://user-images.githubusercontent.com/10458215/56142979-3a749300-5fd2-11e9-83b4-003c02dac18a.png)

**Comment by blackwuxin** [comment]
ReactNative 0.59 要求支持node>=8.3。先使用`node -v`确认下你本机的node版本。

**Comment by xiamingyu** [comment]
![image](https://user-images.githubusercontent.com/10458215/56256989-6f313900-60fd-11e9-8650-a5ae86425021.png)
![image](https://user-images.githubusercontent.com/10458215/56257010-7c4e2800-60fd-11e9-8a62-64520938ca43.png)
node 版本11.6，demo是用crn-cli生成的，不管是用react-native-cli 还是用crn-cli都起不来

**Comment by xiamingyu** [comment]
node版本换v8.3.0,报错相同

**Comment by blackwuxin** [comment]
访问url为`http://127.0.0.1:8081/index.bundle?platform=ios&CRNModuleName=CRNDemo&CRNType=1`或者`http://127.0.0.1:8081/index.bundle?platform=android&CRNModuleName=CRNDemo&CRNType=1`

**Comment by xiamingyu** [comment]
![image](https://user-images.githubusercontent.com/10458215/56412279-31c3db80-62b6-11e9-9994-a25e014b14b2.png)
