### ISSUE TITLE
点击“添加并加载在线地址”报错

### ISSUE THREAD

**Issue by s3hengwu** [ctripcorp/CRN#15]
![4](https://user-images.githubusercontent.com/8500025/56177378-05e3f400-6031-11e9-86a0-99c23cc0a8fc.jpg)

**Comment by blackwuxin** [comment]
`crn-cli start`启动服务默认是8081 ，android使用真机情况要保证手机wifi和你本地服务在同一个网段下。

对应可以使用手机浏览器访问`http://[IP]:80801/index.bundle?platform=android&CRNModuleName=CRNDemo&CRNType=1`验证下服务是否相通。

**Comment by s3hengwu** [comment]
我是电脑开的共享wifi，然后手机连的。应该是同一个网段下吧
