### ISSUE TITLE
Android Runtime接入文档的补充

### ISSUE THREAD

**Issue by tracyxia716** [ctripcorp/CRN#16]
我已经在我的现有项目接入了。针对文档中不太详细的描述，补充一下，希望携程的大佬们能及时完善一下文档，更方便大家接入。
* 1.在settings.graldle添加
```
include ':ReactAndroid',':crnbase'
project(':ReactAndroid').projectDir = new File(rootProject.projectDir, './rnSource/ReactAndroid')
```
在gradle里引入是 implementation project(':crnbase')不是 implementation project(':base')
* 2.如果需要通过ReactAndroid来进行编译的话，需要在根目录下的gradle.properties里配置useReactAndroidSource=true，同时配置NDK环境。（但是编译会比较耗时）
* 3.如果不想要通过ReactAndroid源码来进行编译，就把CRN工程的repo目录拷贝进来，useReactAndroidSource设置为false。同时Android Native项目根目录下gradle  allprojects里的repositories里添加      
```
maven {url = "$rootDir/repo" }。
```

**Comment by chufengma** [comment]
感谢反馈~
