### ISSUE TITLE
about "666666"

### ISSUE THREAD

**Issue by zcgit** [ctripcorp/CRN#19]
![image](https://user-images.githubusercontent.com/4095225/56264460-1ff90180-6119-11e9-9dc9-7cc88a60d221.png)
这个“666666”使用的时候需要什么特殊注意么？我看代码的意思是“业务模块ID应>=666666”。

**Comment by blackwuxin** [comment]
1、crn修改了官方生成模块ID的规则，react-native模块从0开始，业务模块从666666开始。对应参考：`CRN/packages/crn-cli/commands/pack/patch/metro/crn/crn-createModuleIdFactory.js`
2、打业务包的时候会剔除模块ID<666666的模块。这部分模块已经在`rn_common`里面包含了。
3、实际APP加载业务的时候会先加载`rn_common`里面的模块在加载`rn_CRNDemo`的模块。
