### ISSUE TITLE
请问会开源CRN的View组件和API组件吗？

### ISSUE THREAD

**Issue by basilbai** [ctripcorp/CRN#2]
如题！
感谢CRN的开源！！！

**Comment by jimzhao2012** [comment]
这次开源的主要是性能优化部分，对业务开发基本是透明的。
CRN通用的View和API组件开源还在计划评估中，应该不会太晚，具体时间待定哈。

**Comment by raykle** [comment]
支持！
期待看到一些对系统组件优化过的组件，比如 `FlatList` 等

**Comment by shexianseng** [comment]
期待能看到 CRNListView 组建开源
