### ISSUE TITLE
crn-cli run-android 闪退问题

### ISSUE THREAD

**Issue by thisSillyCow** [ctripcorp/CRN#20]
crn-cli run-android  应用安装成功之后 应用启动之后 直接闪退  请问这个要怎么解决

**Comment by thisSillyCow** [comment]
型号: lenovo K52e78  Android版本：6.0 
我用小米测试是正常的

**Comment by weimanleung** [comment]
是android\app\src\main\res\values\color.xml 文件里的、
<color name="colorPrimary">#a1277ee9</color>
<color name="colorPrimaryDark">#a1277ee9</color>
这两个颜色值出错了，可以把它删掉或者不要设置alpha的值

**Comment by janceChun** [comment]
删掉还是闪退= =。 oppo r11， android 7.1.1

**Comment by weimanleung** [comment]
> 删掉还是闪退= =。 oppo r11， android 7.1.1

在Android Studio 里跑项目，看错误日志。

**Comment by chenfeixiang** [comment]
> 是android \ app \ src \ main \ res \ values \ color.xml文件里的，colorPrimary和colorPrimaryDark 
> 这两个颜色值导致，可以把它删掉或者不要设置alpha的值。
> 如果删掉，则需要同时对应修改res \ values \ styles.xml里引用到colorPrimary和colorPrimaryDark

删除值后，可以运行起来了
