### ISSUE TITLE
热更新支持

### ISSUE THREAD

**Issue by ChrislosChen** [ctripcorp/CRN#23]
CRN自定义的打包方案，理论上应该上不支持code-push热更新的吧，如果要支持热更新，后续CRN会考虑支持吗

**Comment by zlpcloud** [comment]
支持的。
大致方案是：
1、客户端用本地rn包的packageId向服务端请求增量
2、服务端比较客户端基准包与最新包的差异，生成diff文件下发
3、客户端merge diff
因为热更新这部分跟内部打包发布系统相关联，所以没有开源。
