### ISSUE TITLE
crn-cli: command not found

### ISSUE THREAD

**Issue by keepJion** [ctripcorp/CRN#28]
执行了 npm install -g crn-cli ，但是报错

**Comment by hu-qi** [comment]
![image](https://user-images.githubusercontent.com/17986122/57290374-ddab5a80-70ef-11e9-8231-6bd71a0df941.png)

win10下没问题
- node v10.14.1
- npm v6.5.0
- taobao镜像

建议您补充报错信息

**Comment by keepJion** [comment]
![image](https://user-images.githubusercontent.com/14191891/57907048-afc3d400-78ae-11e9-872d-a60ed297a012.png)
不好意思，忘记回复了。

**Comment by ldnjun** [comment]
> ![image](https://user-images.githubusercontent.com/14191891/57907048-afc3d400-78ae-11e9-872d-a60ed297a012.png)
> 不好意思，忘记回复了。

执行:cd /usr/local/bin/ && ln -s /usr/local/Cellar/node/10.6.0/bin/crn-cli
