### ISSUE TITLE
ContextHolder.context 为空

### ISSUE THREAD

**Issue by hejun041** [ctripcorp/CRN#31]
然后在PackageManager 里的各种引用报错
'java.io.File android.content.Context.getFilesDir()' on a null object reference

**Comment by chufengma** [comment]
需要在启动逻辑中加入ContextHolder的初始化逻辑，具体参考：

[README](https://github.com/ctripcorp/CRN/commit/f6768088c8b38dc2ec255f4f1658b7de3ba07b6e)

[BaseApplication](https://github.com/ctripcorp/CRN/blob/master/Android/app/src/main/java/ctrip/wireless/android/crn/BaseApplication.java)
