### ISSUE TITLE
react native android第三方包引入问题

### ISSUE THREAD

**Issue by kfayay** [ctripcorp/CRN#34]
- react-native link 第三方包 android引入报错
crn对于android的MainActivity重新实现了，这样子导致引入第三方包失败，这样的问题如何解决呢

**Comment by chufengma** [comment]
可以采用手动link的方式：

##### 在 `Android/crnbase/build.gradle` 中,  添加第三方库的Android依赖

```diff
dependencies {
+    compile project(':[第三方库]')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
}
```

##### 在 `Android/settings.gradle` 中
```diff
include ':app'
+ include ':[第三方库]'
+ project(':第三方库').projectDir = new File(rootProject.projectDir, '../node_modules/第三方库的具体路径')
```

##### 在 `Android/crnbase/src/main/java/ctrip/wireless/android/crn/extend/CRNProvider.java`,中加入第三方库对应的Package的依赖 
```diff


public class CRNProvider {

    public static List<ReactPackage> provideReactPackages() {
        // TODO 在此加入Packages
        List list = new ArrayList();
        list.addAll(Arrays.asList(
                new MainReactPackage(),
+              new [ThirdPartPackage]()
        ));
        return list;
    }

}

```

**Comment by kfayay** [comment]
@chufengma @blackwuxin  感谢你的解答。
同样是使用第三方包，react navigation 依赖的react-native-gesture-handler。
对于gesture-handler手动link碰到了两个问题
- 需要对ReactRootView进行处理，这个地方我在CRNBaseFragment.java文件的onReactInstanceLoaded方法中进行了处理
`mReactRootView = new RNGestureHandlerEnabledRootView(getActivity());`
这个地方不知道对不对。
- 另一个问题是，CRN对react native的依赖重新进行了处理，导致在编译的时候报错无法找到依赖包，报错信息如下
`node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerModule.java:16: 错误: 程序包com.facebook.react.module.annotations不存在
import com.facebook.react.module.annotations.ReactModule;`
