### ISSUE TITLE
lazyRequire 怎么和开源的路由库结合呢 比如说react-navigation

### ISSUE THREAD

**Issue by RaySaii** [ctripcorp/CRN#36]

**Comment by chufengma** [comment]
lazyRequire ：
```
LazyModule module = lazyRequire('xxx');

LazyModule = {
   function load() {
       if (loaded) {
           return module;
       } else {
           // do load
       }
    
   }
}
```
在具体路由库跳转页面之前调用lazyModule的load方法即可。

**Comment by moseszhou** [comment]
react-navigation 在配置的时候需要
const pages={home: {
        screen: require("./page/home")
    },
subpage:{screen:require('./page/subpage')}
}
createStackNavigator(pages,config),那么这里pages应该都是加载了吧，请问如何解决这个问题，比如一开始我只希望只是加载home的，其他页面在跳转的时候动态加载，请问如何配置？

**Comment by moseszhou** [comment]
react-navigation 在配置的时候需要
`const pages={
            home: {
                     screen: require("./page/home")
            },
           subpage:{
                     screen:require('./page/subpage')}
           }
   }` 

createStackNavigator(pages,config),那么这里pages应该都是加载了吧，请问如何解决这个问题，比如一开始我只希望只是加载home的，其他页面在跳转的时候动态加载，请问如何配置？
