### ISSUE TITLE
打包成线上包，怎么去掉CRNDemo这层

### ISSUE THREAD

**Issue by fangcaiwen** [ctripcorp/CRN#39]
您好，这个app开发好，怎么直接加在crn bundle，而去掉CRN Demo这层？

**Comment by sunfengbiao** [comment]
没太明白你的意思 ，能具体的描述下

**Comment by fangcaiwen** [comment]
> 没太明白你的意思 ，能具体的描述下

您好，非常感谢您为我回答。现在初始化的项目不是有CRNDemo选择用哪个bundle这一层吗，实际开发一个app肯定是不需要这一层的，那么这一层是原生来把它替换成欢迎页还是怎么做？

**Comment by blackwuxin** [comment]
这样要根据你实际业务需求。
例如，APP启动后先进入首页，首页点击按钮再访问具体二级页面。这个首页和二级页面都可以是RN页面。
