### ISSUE TITLE
怎么分模块打包

### ISSUE THREAD

**Issue by fangcaiwen** [ctripcorp/CRN#40]
您好，怎么根据不同模块分别打包不同的crn bundle

**Comment by blackwuxin** [comment]
假设我们有两个业务，它们分别是通过`crn-cli init flight`和`crn-cli init bus`创建的。
我们分别进入`flight`和`bus`目录执行`crn-cli pack`。这时候会在工程目录生成对应打包后产物`publish`里面有`rn_common`和`rn_flight`,`rn_bus`。其中`rn_common`是公共部分，`rn_flight`和`rn_bus`对应业务包。
总结: 进入不同的工程目录，分别执行`crn-cli pack`进行打包。

**Comment by fangcaiwen** [comment]
> 假设我们有两个业务，它们分别是通过`crn-cli init flight`和`crn-cli init bus`创建的。
> 我们分别进入`flight`和`bus`目录执行`crn-cli pack`。这时候会在工程目录生成对应打包后产物`publish`里面有`rn_common`和`rn_flight`,`rn_bus`。其中`rn_common`是公共部分，`rn_flight`和`rn_bus`对应业务包。
> 总结: 进入不同的工程目录，分别执行`crn-cli pack`进行打包。

您好，非常感谢您的回答。这样建立两个项目是可以这样，那假如一个项目里，有三个模块，分别打包，有好的方法吗？
