### ISSUE TITLE
base.mapping如何编写

### ISSUE THREAD

**Issue by colinNaive** [ctripcorp/CRN#41]
请问base.mapping是一点点写的吗？还是自动生成的？将近400个id...

**Comment by blackwuxin** [comment]
通过代码自动生成。metro打包的时候会在内部生成一个模块依赖表，对应改造下生成base.mapping文件即可。

**Comment by colinNaive** [comment]
你好 对应的代码在什么地方呢？还是不太理解

**Comment by blackwuxin** [comment]
basemapping生成代码路径：
CRN/packages/crn-cli/commands/pack/patch/metro/crn/crn-createModuleIdFactory.js
全局搜索 `basemapping` 可以查看到使用地方。
