### ISSUE TITLE
能否增加typescript支持?

### ISSUE THREAD

**Issue by figorchen** [ctripcorp/CRN#46]

**Comment by blackwuxin** [comment]
目前我们这样使用typescript的：
 代码直接使用ts编写，打包的时候先执行ts build生成JS代码，打包入口文件引用.js文件。
 简化操作可以在package.json中添加自动编译ts，具体如下：
"scripts": {
 "postinstall": "npm run buildts",
 "dev": "npm run build-ts-watch",
 "buildts": "echo '编译typescript文件。。。请稍等' && tsc",
 "build-ts-watch": "echo '编译typescript文件。。。请稍等' && tsc -w"
}
