### ISSUE TITLE
会支持rn和原生分离么

### ISSUE THREAD

**Issue by Mr-jiangzhiguo** [ctripcorp/CRN#47]
想要实现像h5那样的模式（无需发包）：
前端人员只需要把rn页面打包成bundle（带hash），上传到服务器。
原生人员则只需要下载bundle比较hash来进行热更新（无需发包）。

这种的目前可以实现么？？？

**Comment by blackwuxin** [comment]
可以实现。
思路和hybird包更新一样。APP启动的时候去服务端获取业务包列表，下载业务包。进入的业务模块的时候，解压缩，访问对应jsbundle文件。
更进一步可以做到增量下载。请求服务端的时候，APP把包内业务版本号上传的，服务端对比最新版本业务包，生成diff后的增量包下发。APP获取增量包后，合并生成完整业务包文件。
