### ISSUE TITLE
react-native-gesture-handler 引入报错

### ISSUE THREAD

**Issue by jzyds** [ctripcorp/CRN#48]
> Task :react-native-gesture-handler:compileDebugJavaWithJavac FAILED

**Comment by hanliuxin5** [comment]
能多有一些报错信息吗？

比如你在哪个步骤里出现的这个错误？

**Comment by blackwuxin** [comment]
react-native-gesture-handler组件分为两部分，一部分是native代码，一部分是js。先完成native代码的导入，再在JS代码使用该库。
