### ISSUE TITLE
cli 模板有问题，server bundle 路径有问题

### ISSUE THREAD

**Issue by MrPluto** [ctripcorp/CRN#5]
cli 的模板 package.json 里边的 script 应该是 crn-cli xxx 吧？
另外 启动 bundle server，路径在 `./project_name/__tmp` 目录下，应该在 `./project_name` ？

**Comment by blackwuxin** [comment]
fix in [3e76012 ](https://github.com/ctripcorp/CRN/commit/a95c13790ed710cfb109ecc6648bf99e1c46cf31) 

通过`crn-cli start`启动服务主要做两件事：
 1、在当前工程目录创建一个`__tmp`文件夹，写入脚本文件`launchPackager.command`和`packager.sh`
 2、执行`launchPackager.command`启动服务。
所以，启动bundle server的路径在`./project_name/__tmp`目录下。

**Comment by MrPluto** [comment]
@blackwuxin 但是 index.js 入口文件是在 ./project_name 下

**Comment by blackwuxin** [comment]
你说的没错，项目入口`index.js`是在`./project_name`目录下。

比较合理做法是从`__tmp`目录切换到`./project_name`目录下，再启动服务。

为什么现有`crn-cli start`启动服务的时候也可以正常访问呢？到`@react-native-community/cli@1.5.0`才传入了`projectRoot`参数到`metro`中[#259](https://github.com/react-native-community/cli/pull/259)。而`crn-cli init `创建模板工程时候，指定依赖版本`@react-native-community/cli@1.4.5`，在`start`的是也检查了`@react-native-community/cli`版本，对应版本号大于等于`1.5.0`多传入了`--projectRoot`进行跟目录设置。

我们会在下个版本修改下启动服务，先切换到工作目录在执行启动服务。感谢反馈。

**Comment by shukaka** [comment]
现在手动修改服务启动路径，会被cli覆盖掉无法生效，但是不修改的话一直报错，因为入口文件在./project_name目录下,crn却去__tmp目录中寻找，导致找不到入口文件而报错。
要怎么解决这个问题呢？
