### ISSUE TITLE
感觉这里多删了代码，有点问题，上面少了一个else？

### ISSUE THREAD

**Issue by wods** [ctripcorp/CRN#6]
https://github.com/ctripcorp/CRN/blob/496c0640e85f22706e53f19de02e18648259ff71/iOS/CRNDemo/CRNDemo/CRN/CRN/Model/CRNURL.m#L82

**Comment by zlpcloud** [comment]
少删了部分代码，这部分逻辑已经不用了。已简化代码 in [a28e1b7a](https://github.com/ctripcorp/CRN/commit/a28e1b7aaa73883dfb6f0e58766c9fc8ddcbf825)
