### ISSUE TITLE
如何在js打包多业务

### ISSUE THREAD

**Issue by tracyxia716** [ctripcorp/CRN#8]
非常感谢携程的开源。
看了一下crn-cli的代码，目前pack命令只支持生成common+一个业务。如果想要生成一个common+多个业务，应该如何配置js文件和打包呢？

**Comment by blackwuxin** [comment]
1、可以考虑写一个shell脚本，切换到多个业务工程目录，分别执行`crn-cli pack`进行打包。
2、`crn-cli pack`新增参数，支持传入多个业务工程目录，内部切换到不同业务工程目录，再分别打包。

**Comment by tracyxia716** [comment]
> 1、可以考虑写一个shell脚本，切换到多个业务工程目录，分别执行`crn-cli pack`进行打包。
> 2、`crn-cli pack`新增参数，支持传入多个业务工程目录，内部切换到不同业务工程目录，再分别打包。

好的，朝着这个方向尝试一下

**Comment by ChrislosChen** [comment]
> 1、可以考虑写一个shell脚本，切换到多个业务工程目录，分别执行`crn-cli pack`进行打包。
> 2、`crn-cli pack`新增参数，支持传入多个业务工程目录，内部切换到不同业务工程目录，再分别打包。

切换到多个业务工程目录，那就是每一个业务都需要一个单独都工程了？

**Comment by blackwuxin** [comment]
是否每个业务都需要一个单独工程这个要看具体场景。

一个工程对应一个业务包，对应一个RN容器。

如果一个业务下有多个子业务，复杂度比较高，可以拆成一个单独的工程。反之，简单的业务使用一个工程也是可以的。

**Comment by moseszhou** [comment]
多个业务包工程，分别执行crn-cli pack进行打包，打包出来的crn_common是一样的么？ 可以把多个工程中生成好的rn_CRNDemo（业务包），配合其中某个工程的rn_common使用么？我担心不同工程打出来的crn_common不一致导致，在调用某个业务包的时候，对应的moudle_id找不到，或者找到的是不对的js文件。请帮我解惑，谢谢！
